# Generated by Django 3.0.5 on 2020-04-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200423_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decs',
            new_name='desc',
        ),
    ]
